#!/usr/bin/env node
/**
 * RepoScope GitHub Action runner — zero dependency (no @actions/* packages).
 *
 * 1. Resolve changed files (git diff against base_ref)
 * 2. Incrementally build the module dependency graph (reuses .reposcope-cache.json)
 * 3. Compute blast radius for the changed modules
 * 4. Emit a Markdown impact report
 * 5. Post it as a PR comment (via Node's built-in https), or print to stdout
 *
 * Works both inside GitHub Actions (with GITHUB_* env) and locally (no env →
 * prints the report, so you can develop the action on your machine).
 */
import fs from 'node:fs';
import path from 'node:path';
import https from 'node:https';
import { spawnSync } from 'node:child_process';
import { buildGraphIncremental, blastRadius, collectSources } from './analyze.mjs';
import { isAvailable, generate, buildChangeSummaryPrompt } from './ollama.mjs';

const repoPath = process.env.INPUT_PATH || '.';
const token = process.env.INPUT_TOKEN || process.env.GITHUB_TOKEN || '';
const CODE_EXT = new Set(['.js', '.jsx', '.ts', '.tsx', '.mjs', '.cjs', '.py', '.go', '.rs']);

/* ---------- inputs / event context ---------- */
function readEvent() {
  try { return JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8')); }
  catch { return {}; }
}
function baseRef() {
  if (process.env.INPUT_BASE_REF) return process.env.INPUT_BASE_REF;
  const ev = readEvent();
  return ev?.pull_request?.base?.ref || 'main';
}
function prNumber() {
  const ev = readEvent();
  return ev?.pull_request?.number || ev?.number || null;
}

/* ---------- git diff → changed code files ---------- */
function changedFiles() {
  const base = baseRef();
  const a = spawnSync('git', ['diff', '--name-only', `${base}...HEAD`], { cwd: repoPath, encoding: 'utf8' });
  let out = a.stdout || '';
  if (a.status !== 0) {
    const b = spawnSync('git', ['diff', '--name-only', 'HEAD~1'], { cwd: repoPath, encoding: 'utf8' });
    out = b.stdout || '';
  }
  return out.split('\n').map((s) => s.trim()).filter(Boolean)
    .filter((f) => CODE_EXT.has(path.extname(f)));
}

/* ---------- markdown report ---------- */
function report(g, changed, r, summary) {
  const changedMods = r.changed;   // module-level set of changed files (from blastRadius)
  const pct = g.cache.hit;
  let md = '## 🛰️ RepoScope — PR architecture impact\n\n';
  md += `Analyzed **${g.files}** files (**${g.edges.length}** module edges) · ` +
        `incremental cache **${pct}%** hit (${g.cache.scanned} re-scanned, ${g.cache.reused} reused).\n\n`;
  if (summary) {
    md += `**AI summary**\n\n${summary}\n\n`;
  }
  md += `**Changed modules (${changedMods.length})**\n` +
        (changedMods.length ? changedMods.map((m) => `- \`${m}\``).join('\n') : '- none (non-code changes)\n');
  md += '\n\n**Directly impacted (1 hop)**\n' +
        (r.direct.length ? r.direct.map((m) => `- \`${m}\``).join('\n') : '- none\n');
  md += '\n\n**Transitively impacted**\n' +
        (r.transitive.length ? r.transitive.map((m) => `- \`${m}\``).join('\n') : '- none\n');
  md += '\n\n---\n_Generated by [RepoScope](https://github.com/reposcope/reposcope), local-first code map for agents._\n';
  return md;
}

/* ---------- post PR comment via GitHub REST API (https, zero dep) ---------- */
function postComment(repo, pr, body) {
  return new Promise((resolve) => {
    const data = JSON.stringify({ body });
    const req = https.request({
      hostname: 'api.github.com',
      path: `/repos/${repo}/issues/${pr}/comments`,
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'reposcope-action',
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data),
      },
    }, (resp) => {
      let d = '';
      resp.on('data', (c) => (d += c));
      resp.on('end', () => resolve({ status: resp.statusCode, body: d }));
    });
    req.on('error', (e) => resolve({ status: 0, body: e.message }));
    req.write(data);
    req.end();
  });
}

/* ---------- main ---------- */
(async () => {
  const changed = changedFiles();
  const g = buildGraphIncremental(repoPath);
  const r = blastRadius(g, changed);

  let summary = '';
  if (await isAvailable()) {
    const mods = [...new Set([...r.changed, ...r.direct, ...r.transitive])].filter((m) => g.moduleFiles[m]);
    const sources = collectSources(repoPath, g, mods);
    try { summary = await generate(buildChangeSummaryPrompt(changed, r, sources)); }
    catch (e) { process.stderr.write(`reposcope: LLM summary failed (${e.message}); using structured report\n`); }
  }

  const md = report(g, changed, r, summary);

  const reportPath = path.join(repoPath, 'reposcope-report.md');
  try { fs.writeFileSync(reportPath, md); } catch { /* may be read-only */ }

  const pr = prNumber();
  const repo = process.env.GITHUB_REPOSITORY;
  if (pr && repo && token) {
    const res = await postComment(repo, pr, md);
    process.stderr.write(`reposcope: posted comment to ${repo}#${pr} → HTTP ${res.status}\n`);
  } else {
    // local / non-PR mode: just surface the report
    process.stdout.write(md + '\n');
  }
})();
